#if (ARDUINO >= 100)
	#include "Arduino.h" // for Arduino 1.0
#else
	#include "WProgram.h" // for Arduino 23
#endif

#include "Goldelox_Serial_4DLib.h"
//#include "Goldelox_Types4D.h"	         	// Defines for 4dgl constants, generated by conversion of 4DGL constants to target language
//#include "Goldelox_Const4DSerial.h"        	// Defines for 4dgl constants, generated by conversion of 4DGL constants to target language
#include "Goldelox_Const4D.h"	         	// Defines for 4dgl constants, generated by conversion of 4DGL constants to target language

// WARNING, this code will crash if newval exceeds maximum displayable number
void LedDigitsDisplay(Goldelox_Serial_4DLib Display, word newval, word indexH, word indexL, word left, word top, word Digits, word MinDigits, word WidthDigit, word LeadingBlanks)
{
  word i, k, l, lb ;
  l = 1 ;
  for (i = 1; i < Digits; i++)
    l *= 10 ;
  lb = LeadingBlanks ;
  for (i = 0; i < Digits; i++)
  {
    k = newval / l ;
    newval -= k * l ;
    if ( lb && (i < Digits - MinDigits) )
    {
      if (k == 0)
        k = 10 ;
      else
        lb = 0 ;
    }
    l /= 10 ;
    Display.media_SetAdd(indexH, indexL) ;
    Display.media_VideoFrame(left+i*WidthDigit, top, k) ;
  }
}

void LedDigitsDisplayD(Goldelox_Serial_4DLib Display, word newval, word indexH, word indexL, word left, word top, word Digits, word MinDigits, word WidthDigit, word LeadingBlanks)
{
  word i, k, l, lb ;
  l = 1 ;
  for (i = 1; i < Digits; i++)
    l *= 10 ;
  lb = LeadingBlanks ;
  for (i = 0; i < Digits; i++)
  { 
    k = newval / l ;
    newval -= k * l ;
    if ( lb && (i < Digits - MinDigits) )
    {
      if (k == 0)
        k = 10 ;
      else
        lb = 0 ;
    }
    l /= 10 ;
    Display.media_SetAdd(indexH, indexL) ;
    Display.media_VideoFrame(left-i*WidthDigit+(Digits-1)*WidthDigit+6, top, k) ;
  }
}

void LedDigitsDisplayR(Goldelox_Serial_4DLib Display, word newval, word indexH, word indexL, word left, word top, word Digits, word MinDigits, word WidthDigit, word LeadingBlanks)
{
  word i, k, l, lb ;
  l = 1 ;
  for (i = 1; i < Digits; i++)
    l *= 10 ;
  lb = LeadingBlanks ;
  for (i = 0; i < Digits; i++)
  {
    k = newval / l ;
    newval -= k * l ;
    if ( lb && (i < Digits - MinDigits) )
    {
      if (k == 0)
        k = 10 ;
      else
        lb = 0 ;
    }
    l /= 10 ;
    Display.media_SetAdd(indexH, indexL) ;
    Display.media_VideoFrame(left, top-i*WidthDigit+(Digits-1)*WidthDigit+6,k) ;
  }
}

void LedDigitsDisplayL(Goldelox_Serial_4DLib Display, word newval, word indexH, word indexL, word left, word top, word Digits, word MinDigits, word WidthDigit, word LeadingBlanks)
{
  word i, k, l, lb ;
  l = 1 ;
  for (i = 1; i < Digits; i++)
    l *= 10 ;
  lb = LeadingBlanks ;
  for (i = 0; i < Digits; i++)
  {
    k = newval / l ;
    newval -= k * l ;
    if ( lb && (i < Digits - MinDigits) )
    {
      if (k == 0)
        k = 10 ;
      else
        lb = 0 ;
    }
    l /= 10 ;
    Display.media_SetAdd(indexH, indexL) ;
    Display.media_VideoFrame(left, top+i*WidthDigit,k) ;
  }
}

